# Используем официальный образ Ruby
FROM ruby:3.1.3

# Устанавливаем зависимости для работы с Rails
RUN apt-get update -qq && apt-get install -y nodejs

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем Gemfile и Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Устанавливаем гемы
RUN bundle install

# Копируем все остальные файлы приложения
COPY . .

# Открываем порт, на котором будет работать приложение
EXPOSE 3000

# Команда для запуска приложения
CMD ["rails", "server", "-b", "0.0.0.0"]
